'use client'

import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'

interface FAQItem {
  question: string
  answer: string
}

const faqs: FAQItem[] = [
  {
    question: 'How do I create a QR code?',
    answer: 'Creating a QR code is simple: 1) Enter your URL or text in the input field, 2) Customize the foreground and background colors if desired, 3) Select your preferred format (PNG, SVG, or JPG), 4) Click the Generate button, 5) Download your QR code instantly. No sign-up or payment required.',
  },
  {
    question: 'Is this QR code generator really free?',
    answer: 'Yes, this QR code generator is completely free forever. Unlike other QR code tools, we don\'t charge for basic features, add watermarks, require sign-ups, or limit the number of QR codes you can create. All features are available to everyone at no cost.',
  },
  {
    question: 'What formats can I download my QR code in?',
    answer: 'You can download your QR code in three formats: PNG (best for web and digital use), SVG (vector format, best for print and scaling), and JPG (compressed format, smaller file size). Choose the format that best suits your needs.',
  },
  {
    question: 'Can I customize the colors of my QR code?',
    answer: 'Yes! You can customize both the foreground (dark squares) and background (light area) colors of your QR code. Use the color pickers to choose any color you want, or enter a hex code directly. Make sure there\'s enough contrast between colors for reliable scanning.',
  },
  {
    question: 'Are there any watermarks on the generated QR codes?',
    answer: 'No, there are no watermarks whatsoever. Your QR codes are completely clean and professional. You can use them for commercial purposes, print materials, business cards, or any other use case without any branding from our tool.',
  },
  {
    question: 'Is my data safe? Do you collect information?',
    answer: 'Your data is completely safe because we don\'t collect it. All QR code generation happens locally in your browser (client-side). Your URLs and content never leave your device. We don\'t store, track, or have access to any information you enter.',
  },
  {
    question: 'Can I use these QR codes for commercial purposes?',
    answer: 'Yes, you can use the QR codes generated by this tool for any purpose, including commercial use. There are no restrictions or licenses required. Use them in your business, marketing materials, products, or anywhere else you need.',
  },
  {
    question: 'What\'s the difference between PNG, SVG, and JPG formats?',
    answer: 'PNG is a lossless format ideal for digital use with transparent backgrounds if needed. SVG is a vector format that can scale to any size without losing quality, perfect for printing. JPG is a compressed format with smaller file sizes, good for web use where file size matters. We recommend PNG for most digital uses and SVG for print.',
  },
]

function FAQItem({ faq, isOpen, onToggle }: { faq: FAQItem; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="border-b border-foreground/10">
      <button
        onClick={onToggle}
        className="w-full text-left py-6 px-4 flex items-start justify-between gap-4 hover:bg-foreground/5 transition-colors"
        aria-expanded={isOpen}
      >
        <h3 className="text-lg font-medium text-foreground pr-4">{faq.question}</h3>
        <ChevronDown
          className={cn(
            'w-5 h-5 text-primary transition-transform duration-300 flex-shrink-0 mt-1',
            isOpen && 'rotate-180'
          )}
        />
      </button>
      <div
        className={cn(
          'overflow-hidden transition-all duration-300 ease-in-out',
          isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
        )}
      >
        <div className="px-4 pb-6 text-foreground/80 leading-relaxed">
          {faq.answer}
        </div>
      </div>
    </div>
  )
}

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <section id="faq" className="w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
      <div className="text-center mb-12">
        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-4">
          Frequently Asked Questions
        </h2>
        <p className="text-lg text-foreground/70 max-w-2xl mx-auto">
          Everything you need to know about our free QR code generator
        </p>
      </div>

      <div className="bg-background border border-foreground/10 rounded-lg overflow-hidden shadow-sm">
        {faqs.map((faq, index) => (
          <FAQItem
            key={index}
            faq={faq}
            isOpen={openIndex === index}
            onToggle={() => toggleFAQ(index)}
          />
        ))}
      </div>
    </section>
  )
}
